name          'opentable-graphite_powershell'
version       '0.1.0'
source        'git://github.com/opentable/puppet-graphite_powershell'
author        'opentable'
summary       'Module to send metrics to graphite from windows'
description   'Installs a windows service that reports system metrics to graphite'
project_page  'https://github.com/opentable/puppet-graphite_powershell'
license       'MIT'
dependency    'puppetlabs/stdlib'
